spring.application.name=v1

spring.profiles.active=prod


# Server
server.port=8080

# Hibernate / JPA defaults
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Hikari connection pool defaults
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool

# MVC request logging
spring.mvc.log-request-details=true
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
